Collection = [
{path:'Rise.mp3'},
{path:'example.mp3'},
{path:'example1.mp3'},
{path:'example2.mp3'},
{path:'example3.mp3'},
{path:'example4.mp3'},
{path:'example5.mp3'},
{path:'example6.mp3'},
{path:'example7.mp3'},
{path:'example8.mp3'},
{path:'example9.mp3'},
{path:'example10.mp3'},
{path:'example11.mp3'},
{path:'example12.mp3'},
{path:'example13.mp3'},
{path:'example14.mp3'},
{path:'example15.mp3'},
{path:'example16.mp3'},
{path:'example17.mp3'},
{path:'example18.mp3'},
{path:'example19.mp3'},
{path:'example20.mp3'},
{path:'example21.mp3'},
{path:'example22.mp3'},
{path:'example23.mp3'},
{path:'example24.mp3'},
{path:'01. Attack.mp3'},
{path:'01. Birth.mp3'},
{path:'01. Capricorn (A Brand New Name).mp3'},
{path:'01. Escape.mp3'},
{path:'01. I Like It Like That (feat. New Boyz).mp3'},
{path:'01. Say (Half Past Nine).mp3'},
{path:'01 - BRAND NEW MELODY.mp3'},
{path:'01 - Eternity Love.mp3'},
{path:'01 - Knocking on the mind.mp3'},
{path:'01 - Maigo no Kokoro.mp3'},
{path:'01 - Maji LOVE 1000%.mp3'},
{path:'01 - Nanairo No Compass.mp3'},
{path:'01 - Orion de SHOUT OUT.mp3'},
{path:'01 - Orpheus.mp3'},
{path:'01 - Otokogi Zenkai Go!Fight!!.mp3'},
{path:'01 - Sekai no hate made Believe Heart.mp3'},
{path:'01 На север.mp3'},
{path:'01 Опасное лето.mp3'},
{path:'02. A Beautiful Lie.mp3'},
{path:'02. Conquistador.mp3'},
{path:'02. Edge Of The Earth.mp3'},
{path:'02. I Like To Dance.mp3'},
{path:'02. Night Of The Hunter.mp3'},
{path:'02. Tonight Tonight.mp3'},
{path:'02 - Ai to Yume to Anata to.mp3'},
{path:'02 - Changing our Song!.mp3'},
{path:'02 - Dear...Burning my Lady!.mp3'},
{path:'02 - Mirai Chizu.mp3'},
{path:'02 - MOONLIGHT.mp3'},
{path:'02 - MOST FORTISSIMO.mp3'},
{path:'02 - My Little Little Girl.mp3'},
{path:'02 - Over the Rainbow.mp3'},
{path:'02 - Top Star Revolution.mp3'},
{path:'02 Дорога сна.mp3'},
{path:'03. 23kid.mp3'},
{path:'03. Fallen.mp3'},
{path:'03. Honestly.mp3'},
{path:'03. Kings And Queens.mp3'},
{path:'03. Never Have I Ever.mp3'},
{path:'03. The Kill.mp3'},
{path:'03. Up In The Air.mp3'},
{path:'03 - STAND UP SOUL.mp3'},
{path:'03 Господин горных дорог.mp3'},
{path:'04. Bleed.mp3'},
{path:'04. City Of Angels.mp3'},
{path:'04. Keep You With Me.mp3'},
{path:'04. Oblivion.mp3'},
{path:'04. This Is War.mp3'},
{path:'04. Was It A Dream.mp3'},
{path:'04 Ветер.mp3'},
{path:'04 Травушка.mp3'},
{path:'05. 100 Suns.mp3'},
{path:'05. Buddha For Mary.mp3'},
{path:'05. Bushes.mp3'},
{path:'05. Fix The Sky A Little.mp3'},
{path:'05. Radio (feat. Bei Maejor).mp3'},
{path:'05. The Fantasy.mp3'},
{path:'05. The Race.mp3'},
{path:'05 Ведьма.mp3'},
{path:'06. Echelon.mp3'},
{path:'06. End Of All Days.mp3'},
{path:'06. Hurricane.mp3'},
{path:'06. Problematique.mp3'},
{path:'06. Savior.mp3'},
{path:'06. Whatever.mp3'},
{path:'06 Двери Тамерлана.mp3'},
{path:'07. Closer To The Edge.mp3'},
{path:'07. Forever Unstoppable.mp3'},
{path:'07. From Yesterday.mp3'},
{path:'07. Pires Of Varanasi.mp3'},
{path:'07. The Distance.mp3'},
{path:'07. Welcome To The Universe.mp3'},
{path:'07 Далеко.mp3'},
{path:'07 Огонь.mp3'},
{path:'08. Alright.mp3'},
{path:'08. Bright Lights.mp3'},
{path:'08. The Mission.mp3'},
{path:'08. The Story.mp3'},
{path:'08. Vox Populi.mp3'},
{path:'08. Why Don\'t You Love Me (feat. Demi Lovato).mp3'},
{path:'09. Do Or Die.mp3'},
{path:'09. Downtown Girl.mp3'},
{path:'09. End Of The Beginning.mp3'},
{path:'09. Pierrot The Clown.mp3'},
{path:'09. Queen Of The Scene.mp3'},
{path:'09. R-Evolve.mp3'},
{path:'09. Search And Destroy.mp3'},
{path:'09 Ворожи.mp3'},
{path:'09 Шаман.mp3'},
{path:'10. 93 Million Miles.mp3'},
{path:'10. Alibi.mp3'},
{path:'10. A Modern Myth.mp3'},
{path:'10. Beautiful Freaks.mp3'},
{path:'10. Convergence.mp3'},
{path:'10. Nothing Left To Hide.mp3'},
{path:'10 Волкодав.mp3'},
{path:'10 Прялка.mp3'},
{path:'11. Battle Of One.mp3'},
{path:'11. Last One Standing.mp3'},
{path:'11. Northern Lights.mp3'},
{path:'11. Stranger In A Strange Land.mp3'},
{path:'11. The Only One.mp3'},
{path:'11. Year Zero.mp3'},
{path:'11 Оборотень.mp3'},
{path:'12. Depuis Le Debut.mp3'},
{path:'12. Hunter.mp3'},
{path:'12. L490.mp3'},
{path:'13. Hurricane 2.0 (Feat. Kanye West).mp3'},
{path:'13. The Kill (Rebirth).mp3'},
{path:'13 А Если Бы Он.mp3'},
{path:'14. A Beautiful Lie (Acoustic).mp3'},
{path:'14. Bad Romance (BBC Live Version).mp3'},
{path:'14 Королевна.mp3'},
{path:'15. Stronger (BBC Live Version).mp3'},
{path:'15 Невеста Полоза.mp3'},
{path:'16 Горец.mp3'},
{path:'16 Кувшин.mp3'},
{path:'18 Лента В Волосах.mp3'},
{path:'19 Шелкопряд.mp3'},
{path:'30 Odd Foot Of Grunts - 01 - Things Have Got To Change.mp3'},
{path:'30 Odd Foot Of Grunts - 02 - Memorial Day.mp3'},
{path:'30 Odd Foot Of Grunts - 03 - Hold You.mp3'},
{path:'30 Odd Foot Of Grunts - 04 - Sail Those Same Oceans.mp3'},
{path:'30 Odd Foot Of Grunts - 05 - The Legend Of Barry Kable.mp3'},
{path:'30 Odd Foot Of Grunts - 06 - Somebody Else\'s Princess.mp3'},
{path:'30 Odd Foot Of Grunts - 07 - Wendy.mp3'},
{path:'30 Odd Foot Of Grunts - 08 - The Night That Davey Hit The Train.mp3'},
{path:'30 Odd Foot Of Grunts - 09 - Swept Away Bayou (Facing The Headlights Alone).mp3'},
{path:'30 Odd Foot Of Grunts - 10 - Judas Cart.mp3'},
{path:'96683077-5AEF-4CDB-8C90-A5F2B989C144.jpg'},
{path:'Anna Tsuchiya - MY FATE (NANA OST).mp3'},
{path:'Bana - Shell (OST Witch Hunter Robin).mp3'},
{path:'barsuk.jpg'},
{path:'bird-skull-isolated-white-35989042.jpg'},
{path:'blue_planet_by_yuumei-d62mn5b.jpg'},
{path:'brave_new_world_by_yuumei-d5wprei.jpg'},
{path:'cage_by_yuumei-d33pw18.png'},
{path:'cf8b9742f8ff4003fa726c78ae179d64.jpg'},
{path:'Cher - You Haven’t Seen the Last of Me(OST BURLESQUE-БУРЛЕСК).mp3'},
{path:'cover.jpg'},
{path:'Cowboy Bebop OST-(Steve Conte) - Words that We couldn\'t say.mp3'},
{path:'_ D.Gray-man Opening 3 OST (Access) - Doubt & Trust .mp3'},

{path:'Julie Fowlis - 02. Into the Open Air (Brave OST).mp3'},
{path:'Julie Fowlis - Touch the Sky (OST Храбрая Сердцем).mp3'},
{path:'Kashiwa Daisuke - Greenery Rain (Kotonoha no Niwa OST) .mp3'},
{path:'Kashiwa Daisuke - While Hearing Sound Of Rain (Kotonoha no Niwa OST) .mp3'},
{path:'Loona - Hijo de la luna.mp3'},
{path:'Mandy Moore - Healing Incantation(OST Рапунцель-Запутанная история.mp3'},
{path:'Mandy Moore - When Will My Life Begin OST - Саундтрек - Рапунцель- Запутанная история (2010).mp3'},
{path:'Mika  - Elle me dit .mp3'},
{path:'Motohiro Hata - Kotonoha (Kotonoha no Niwa OST).mp3'},
{path:'Motohiro Hata (Kotonoha no Niwa OST) - Rain (Long Ver.).mp3'},
{path:'Muse - Feeling Good.mp3'},
{path:'Nightwish - Storytime (2011).mp3'},
{path:'Northern Lights - Carolans Ramble to Cashel.mp3'},
{path:'One Republic - Feel Again.mp3'},
{path:'OST Cowboy Bebop - The Real Folk Blues.mp3'},
{path:'Russell Crowe & 30 Odd Foot Of Grunts - 01 - Painted Veil.mp3'},
{path:'Russell Crowe & 30 Odd Foot Of Grunts - 02 - Never Be Alone Again.mp3'},
{path:'Russell Crowe & 30 Odd Foot Of Grunts - 03 - Mission Beat.mp3'},
{path:'Russell Crowe & 30 Odd Foot Of Grunts - 04 - What\'s Her Name-.mp3'},
{path:'Russell Crowe & 30 Odd Foot Of Grunts - 05 - Inside Her Eyes.mp3'},
{path:'Russell Crowe & 30 Odd Foot Of Grunts - 06 - The Same Person.mp3'},
{path:'Russell Crowe & 30 Odd Foot Of Grunts - 07 - Other Ways Of Speaking.mp3'},
{path:'Russell Crowe & 30 Odd Foot Of Grunts - 08 - Full Length Of The River.mp3'},
{path:'Russell Crowe & 30 Odd Foot Of Grunts - 09 - Afraid.mp3'},
{path:'Russell Crowe & 30 Odd Foot Of Grunts - 10 - All The White Circles.mp3'},
{path:'Russell Crowe & 30 Odd Foot Of Grunts - 11 - Unfaithfull Man.mp3'},
{path:'Russell Crowe & 30 Odd Foot Of Grunts - 12 - Charlie\'s Song.mp3'},
{path:'Russell Crowe & 30 Odd Foot Of Grunts - 13 - Swallow My Gift - Farm Noises - Folsom Prison Blues.mp3'},
{path:'Skull_corvus_corone_cropped.jpg'},
{path:'Slava Jamm - The End Never Comes.mp3'},
{path:'Steve Conte (cowboy bebop Ost) - CALL ME, CALL ME.mp3'},
{path:'Taio Cruz - Make It Last Forever.mp3'},
{path:'Taku Iwasaki (Witch Hunter Robin OST)  - Open Your Eyes.mp3'},
{path:'Tori Amos - Horses.mp3'},
{path:'Tori Amos (Тори Эймос)  - Northern Lad.mp3'},
{path:'Vanessa Paradis - La Seine.mp3'},
{path:'Witch Hunter Robin OST - FLAME.mp3'},
{path:'Анна Бутурлина - Отпусти и забудь (OST Холодное сердце).mp3'},
{path:'би-2 feat. вельвеt - научи меня быть счастливым .mp3'},
{path:'Вельвет (Вельвеt) - Все забудется.mp3'},
{path:'Мельница - 6. - Гори, Москва!.mp3'},
{path:'Ширяева Анна (Шмендра) - Королева осени Элис.mp3'},
]

// var root = '/home/roman/Documents/audio3/music/';
var root = '/sdcard/Music/';
for (var i = 0; i < Collection.length; i++) {
	Collection[i].path = root+Collection[i].path;
};